### PR TITLE
DoctrineExclusionStrategy

### PR DESCRIPTION
**Pull request by morgen2009**
DoctrineExclusionStrategy means
- serialization: if entity's id is not null (or not zero), then serialize only the identificator
- deserialization: DoctrineObjectConstructor restores entity from DB using identificator (already implemented)

Also I fixed a bit GraphNavigator.php in the case, if the element is null (use case is some properties of entity are null or omited)

### CODE REVIEW

**Comment by bigfoot90** [comment]
What is the state of this PR?

**Comment by bigfoot90** [comment]
@morgen2009 ping

**Comment by morgen2009** [comment]
If this PR is still usefull, I will rebase it on new serializer (+ tests)

**Comment by bigfoot90** [comment]
It's a cool feature, but it isn't of fundamental importance.

**Comment by goetas** [comment]
Closing this PR as is almost 5 years old and in the meanwhile the serializer changed a lot and partially solved the issue here.

If somebody is still working on this, feel free to re-open a fresh PR

**Pull request closed without merging**
