### PR TITLE
Add ^5.0 in composer.json for symfony dependencies

### PR DESCRIPTION
**Pull request by FabienSalles**
#hackdayparis

### CODE REVIEW

**Comment by goetas** [comment]
you are forgetting https://github.com/schmittjoh/JMSSerializerBundle/blob/9b8d64302770183b41c47d3c38c67aa9ae1c970b/.travis.yml#L12

**Comment by goetas** [comment]
If you are willing to contribute to open-source, I suggest you to read https://www.goetas.com/blog/make-the-difference-when-contributing-to-open-source/ :)

**Comment by FabienSalles** [comment]
> you are forgetting
> 
> https://github.com/schmittjoh/JMSSerializerBundle/blob/9b8d64302770183b41c47d3c38c67aa9ae1c970b/.travis.yml#L12

Thanks for your quick response and sorry for the delay by my side.
It should be ok now !

> If you are willing to contribute to open-source, I suggest you to read https://www.goetas.com/blog/make-the-difference-when-contributing-to-open-source/ 

What would you have wanted me to do to improve my contribution ?

**Comment by goetas** [comment]
Symfony 5.0 has been released, I think that the minimum stability dev rule can be removed now

**Comment by goetas** [comment]
squash merged in https://github.com/schmittjoh/JMSSerializerBundle/commit/209d2a3de1d567be57bddb780a71efba3238ee32

**Pull request closed without merging**
