### PR TITLE
Use public alias for security.authorization_checker service

### PR DESCRIPTION
**Pull request by W0rma**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| Doc updated   | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/schmittjoh/JMSSerializerBundle/issues/854
| License       | MIT

### CODE REVIEW

**Comment by goetas** [comment]
can you see please why tests are failing?

**Comment by W0rma** [comment]
> can you see please why tests are failing?

I missed the fact that `security.authorization_checker` is only available if `symfony/security-bundle` is installed which is not a direct dependency of this package.

Should be fixed with my latest push were the alias is only added if the service `security.authorization_checker` exists.

**Comment by goetas** [comment]
thanks @W0rma !

**Comment by thomaspicquet** [comment]
@goetas would you be able to tag a new release of the bundle to have these changes in a stable version?

**Pull request merged**
