### PR TITLE
fix compatibility with Symfony Config 4.2

### PR DESCRIPTION
**Pull request by xabbuh**
#SymfonyConHackDay2018

### CODE REVIEW

**Comment by goetas** [comment]
Thanks

**Comment by xabbuh** [comment]
@goetas Do you merge `2.x` into `master` or should I send another PR for it?

**Comment by goetas** [comment]
i will do, sorry but I did not have time in the last days

**Comment by xabbuh** [comment]
No worries, I just wasn't sure about the process. :)

**Pull request merged**
