### PR TITLE
Hotfix #657 #663 - 2.x

### PR DESCRIPTION
**Pull request by bpolaszek**

### CODE REVIEW

**Comment by goetas** [comment]
Can you please explain the reason of this change?

**Comment by bpolaszek** [comment]
@goetas Sorry, this is related to #663  - this PR fixes a different behavior between PHP versions, handlers wrongly sorted on PHP7+ and correctly sorted in PHP5.

**Comment by goetas** [comment]
Can you please add some test (by having a big array of listeners)?

**Comment by bpolaszek** [comment]
@goetas Not sure it's worth the work, since we're dealing with a PHP internal. 

`JMS\SerializerBundle\Tests\DependencyInjection\CustomHandlerPassTest::testSubscribingHandlerMustRespectPriorities()` is already written for that, and keep in mind that with `uasort`, the result may, or may not, be what is expected. 

Try out the following snippet (borrowed from `CustomHandlersPass`'s internal code):

```php
// A closure which will always return 0 because all items will have the same 'fixed_value'.
$sorter = function ($a, $b) {
    return $b['fixed_value'] == $a['fixed_value'] ? 0 : ($b['fixed_value'] > $a['fixed_value'] ? 1 : -1);
};

// Copied from CustomHandlersPass
function stable_uasort(array &$array, $value_compare_func)
{
    $index = 0;
    foreach ($array as &$item) {
        $item = [$index++, $item];
    }
    $result = uasort($array, function ($a, $b) use ($value_compare_func) {
        $result = call_user_func($value_compare_func, $a[1], $b[1]);
        return $result == 0 ? $a[0] - $b[0] : $result;
    });
    foreach ($array as &$item) {
        $item = $item[1];
    }
    return $result;
}


// Now, create an array with a fixed value and a random one.
$a = [];
for ($i = 0; $i < 1000; $i++) {
    $a[] = [
        'fixed_value'  => 'foo',
        'random_value' => mt_rand(0, 10000),
    ];
}


$c = $b = $a; // We now have 3 strictly equal arrays
var_dump($b === $a); // true
var_dump($c === $a); // true

// Use PHP built-in sorting function
uasort($b, $sorter); // $b is sorted, but $b is no longer equal to $a
var_dump($b === $a);// false


stable_uasort($c, $sorter); // $c is sorted, and $c is still strictly equal to $a
var_dump($c === $a);// true
```
Tested on PHP 7.2 and PHP 5.6. This confirms what CMB said: Stable sorting is not guaranteed with PHP sort functions, even since PHP7+.

I could write a test with 1000 subscribing handlers, sort them and still have them correctly sorted, the point is that PHP's `uasort()` is clearly unreliable, and in some cases like mine, it will fail. 

The existing `stable_uasort` method is already working and tested with travis on PHP 5+. I have added no code, I just removed the PHP7+ exception.

If you want to be sure that all items are correctly sorted, only the `stable_uasort` function must be unit tested (then it could be subscribing handlers, foo/bars or fruits), but it's currently protected.

I hope you'll understand my point.

Thank you,
Ben

**Comment by goetas** [comment]
alright!

**Pull request merged**
