### PR TITLE
Injected validator.translation_domain to FormErrorHandler

### PR DESCRIPTION
**Pull request by prosalov**
Injected translation domain parameter (validator.translation_domain) to FormErrorHandler. This is a solution suggestion for the following issue: https://github.com/schmittjoh/JMSSerializerBundle/issues/501 and https://github.com/schmittjoh/serializer/pull/783

### CODE REVIEW

**Comment by goetas** [comment]
can you implement this in a backward compatible way? if the serializer is not the latest (the one with your patch), this will not work.

Without tests this can't be merged.

**Comment by goetas** [comment]
what about 

```xml
<argument type="expression">container.hasParameter('some_param') ? parameter('some_param') : 'default_value'</argument>
```
just in the `services.xml` file?

**Comment by prosalov** [comment]
It doesn't work for SF < 2.7

**Comment by goetas** [comment]
thanks!

**Pull request merged**
