### PR TITLE
Fix bad Tag name in error message

### PR DESCRIPTION
**Pull request by lemoinem**
Was `listener` instead of `subscriber`.

### CODE REVIEW

**Comment by lemoinem** [comment]
I'm sorry, did I miss something regarding this PR?

**Comment by lemoinem** [comment]
This PR seems simple enough...

@schmittjoh I understand this is far from critical, but some sort of acknowledgment would be nice. Just to be sure it doesn't slip though the cracks...

**Comment by lemoinem** [comment]
@schmittjoh It's been almost one and a half year... Any news regarding this?

**Comment by goetas** [comment]
Hi, sorry for the terribly long feedback loop. 

Do you mind adding tests for this?

**Comment by lemoinem** [comment]
You really want a test for that? It's just a typo or a copy/paste issue in an error message...

I don't even know how I should test a compiler pass.

How about a compromise: If you can provide a basic test case class for the compiler pass to test its basic behavior, I will add a test case for the error message?

**Comment by goetas** [comment]
alright, let's be pragmatic :) 

An example on how to test compiler passes https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Tests/Compiler/RemoveUnusedDefinitionsPassTest.php

**Comment by lemoinem** [comment]
Thanks for the reference!

I keep my offer on the table. If you ever make available a basic test for the CP, poke me and I will do my best to provide a PR with the test for this error message.

**Pull request merged**
