### PR TITLE
PHP8 support

### PR DESCRIPTION
**Pull request by jacekpl**
Changes based on https://github.com/schmittjoh/JMSSerializerBundle/pull/819 with travis config fix.

### CODE REVIEW

**Comment by Necriso** [comment]
When will this merged?
We are still waiting for it.

**Comment by goetas** [comment]
@jacekpl I think that you've forgot to add the php8 build to the travis matrix

**Comment by goetas** [comment]
thanks!

**Comment by simPod** [comment]
Cool but it's fair to keep commit co-authorship...

**Comment by Necriso** [comment]
Will there be a new version tag?
The last is 2.7.0 from june 2020.

**Comment by alexander-schranz** [comment]
@goetas any possibility to tag a PHP 8 supported version?

**Comment by alexander-schranz** [comment]
@goetas Thx for the release :)

**Pull request merged**
