### PR TITLE
Support for changing default policy

### PR DESCRIPTION
**Pull request by plazmdk**
For use with FOS rest bundle supporting defensive programming not exposing everything in services.

### CODE REVIEW

**Comment by Ener-Getick** [comment]
:-1: a third party bundle can't define which exclusion policy to use by default so this would probably create bugs.

**Comment by goetas** [comment]
@GuilhemN can you elaborate a bit more? i was thinking to include  https://github.com/schmittjoh/serializer/pull/683 sooner of later...

**Comment by goetas** [comment]
but isn't an user choice the default exclusion strategy?

are you worried that the user decides to use a too strict exclusion strategy that can create unexpected behaviors with other bundles that acts as plugins with the serializer?

**Comment by GuilhemN** [comment]
@goetas yes, that's it. Moreover these unexpected behaviors won't be easy to catch.

**Comment by goetas** [comment]
I see your point.

not sure what to do here then :confused:

**Comment by GuilhemN** [comment]
Maybe you can allow to configure this for each bundle, or in each file?

**Comment by goetas** [comment]
currently this is a "per project feature" so can be enabled per any variation of the `config.yml` in symfony.

> or in each file?

if you mean "per entity", this is already possible

per bundle, looks a bit weird..  if you are thinking something as https://symfony.com/doc/current/reference/configuration/assetic.html (per bundle enabler, i find is really weird in this case)

**Comment by GuilhemN** [comment]
I was thinking about the yaml configuration files, it could be possible to add something on top of it. I don't if that's worth it, not if it won't feeling hacky.

Otherwise, you can configure this at the project level with a proper warning but it looks like a technical debt to me as it might break at any time.

**Comment by goetas** [comment]
Closing, merging this will lead to unexpected behaviors since will be possible to change defaults at runtime. Third party libraries will not have a consistent default. 

thanks @GuilhemN for the hint :)

**Pull request closed without merging**
