### PR TITLE
Full Symfony 4 compatibility

### PR DESCRIPTION
**Pull request by goetas**
Will be kept open till the Symfony 4.0 release

### CODE REVIEW

**Comment by GuilhemN** [comment]
Can't this be merged earlier ? It breaks NelmioApiDocBundle tests :/

**Comment by goetas** [comment]
Hmmm... How is possible? Can you point me to a failed build?

**Comment by GuilhemN** [comment]
See https://travis-ci.org/nelmio/NelmioApiDocBundle/jobs/291495489

**Comment by goetas** [comment]
the thing is that sf4 is not yet stable. i've merged months ago already a PR that was "green" but after many changes in the symfony master-dev, a lot of work resulted to be obsolete. 

so I've decided to stop and wait till is stable

**Comment by luishdez** [comment]
I'm not very fan of the policy of don't update or it doesn't have priority because "the related project" final version is not release yet, Sometimes even admins doesn't allow to merge PRs (not saying this is the case…, I know the effort of maintining projects like this)

Having a PR that you merge months ago that have change doesn't look like a disaster. Now Sf4 is beta and Sf doesn't change a lot.

The thing is that most of the time developers use betas to update and test their projects, but if other third parties don't update or doesn't add compatibility in the beta state this is not possible. 

So we have to hold the test and update until the final release or later… And then we can start our testing, this causes a delay chain that in some cases you ended updating your project before the next release is coming

**Comment by juliusstoerrle** [comment]
@luishdez i think while you are right, i can definitely understand @goetas holding back. Time is valuable, we  should not spend it on stuff we can throw away later.
But as you said we are in the late beta stage with the official release date 30th. I do not think there are anymore breaking changes coming and would welcome this bundle to be compatible asap. As i really come to like this bundle, I'm happy to help with PRs and/or debugging.

**Comment by Spea** [comment]
I recently created a new flex project with symfony 4 BETA 4 and tested this branch. But I got some errors regarding missing services, so I digged into it and created a patch for this PR.

https://github.com/schmittjoh/JMSSerializerBundle/compare/sf4-compat...Spea:sf4-compat-patch

As you can see, it is mostly just making services/aliases public. Making subscribers/handlers public is necessary due to the way the [LazyEventDispatcher works](https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/EventDispatcher/LazyEventDispatcher.php#L44-L48).

Let me know if I should do anyhting else here (creating a PR based on this branch?).

**Comment by juliusstoerrle** [comment]
@Spea I think you should do a PR but i'm not a maintainer. WIll test your changes today or tmr!

**Comment by goetas** [comment]
As of yesterday symfony is in RC stage. I guess this can be merged now.

**Comment by naroga** [comment]
Installing jms/serializer-bundle and trying to access either `jms_serializer` from the container, or just letting Symfony autowire from the parameter typehint throws the following exception:

```
The "jms_serializer.metadata_driver" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
 
```

**Comment by goetas** [comment]
@naroga Not really familiar with that error.. :( any symfony folk to help here?

**Comment by goetas** [comment]
Can you try to set [this](https://github.com/schmittjoh/JMSSerializerBundle/blob/master/Resources/config/services.xml#L192) service to public and check if you still have the issue?

**Comment by goetas** [comment]
Alternatively also https://github.com/schmittjoh/JMSSerializerBundle/compare/master...private-aliases could be the solution

**Comment by Spea** [comment]
@goetas Yes, this is the solution and was also in my patch I showed some comments earlier but you should also make the Alias in line 43 public -> https://github.com/schmittjoh/JMSSerializerBundle/blob/master/DependencyInjection/Compiler/DoctrinePass.php#L43

**Comment by naroga** [comment]
> Can you try to set this service to public and check if you still have the issue?

Set the service to public, cleared the cache, ran again, same issue.

> Alternatively also master...private-aliases could be the solution

Made the modification locally, cleared the cache, same issue.

> @goetas Yes, this is the solution and was also in my patch I showed some comments earlier but you should also make the Alias in line 43 public -> https://github.com/schmittjoh/JMSSerializerBundle/blob/master/DependencyInjection/Compiler/DoctrinePass.php#L43

I made the modification locally, to no avail:

    //$container->setAlias($serviceName, $previousId[$serviceName]));
    $container->setAlias($serviceName, new Alias($previousId[$serviceName]), true);

**Comment by goetas** [comment]
@naroga I've created this https://github.com/schmittjoh/JMSSerializerBundle/pull/616 will keep track of issues there

**Pull request merged**
