### PR TITLE
Date deserialization format type(s)

### PR DESCRIPTION
**Pull request by iKsSs**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Doc updated   | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT

### CODE REVIEW

**Comment by iKsSs** [comment]
The new version `v3.31` of JMS Serializer will be released on Monday - 21st Oct 2024

**Review by scyzoryck — APPROVED** [review]

**Comment by scyzoryck** [comment]
@iKsSs Could you take a look at the failing test, please?

**Comment by iKsSs** [comment]
> @iKsSs Could you take a look at the failing test, please?

ofc, should be fixed..

**Comment by iKsSs** [comment]
OK, I fixed the missing 'use' in the test from the previous commit(s)

**Comment by scyzoryck** [comment]
I will take a look - I think I know where the problem is :)

**Review by scyzoryck — APPROVED** [review]

**Comment by scyzoryck** [comment]
Thanks @iKsSs for contribution!

**Pull request merged**
