### PR TITLE
Fix deprecation with Twig 2.7 (2.x branch)

### PR DESCRIPTION
**Pull request by JustBlackBird**
The PR fixes #730 for 2.x branch

### CODE REVIEW

**Comment by JustBlackBird** [comment]
@goetas Could you please tag a new version with the fix?

**Comment by goetas** [comment]
Thanks!

**Comment by JustBlackBird** [comment]
You're welcome! :smile:

**Comment by JustBlackBird** [comment]
@goetas Could you please tag new release with the fix?

**Comment by goetas** [comment]
tagged as 2.4.4

**Comment by JustBlackBird** [comment]
Thank you

**Pull request merged**
