### PR TITLE
support lazily loaded event listeners and handlers

### PR DESCRIPTION
**Pull request by xabbuh**
requires schmittjoh/serializer#844

### CODE REVIEW

**Comment by goetas** [comment]
@xabbuh i've added to your branch the composer dependency on the latest serializer

**Comment by xabbuh** [comment]
Thank you @goetas! Tests are green now. Should I bump the branch alias too?

**Comment by goetas** [comment]
Currently on this project I'm not using the "properly" the branch alias (you can see that is just `2.x-dev`), I guess now should become `2.2-dev`, am I right?

What do you thing, Does it make sense to start using it?

**Comment by xabbuh** [comment]
I think it makes sense. Makes it easier for users depending on the bundle to use proper version constraints.

**Comment by goetas** [comment]
great! thanks! In few hours will release both library and bundle

**Comment by xabbuh** [comment]
Thank you so much! This will allow us to make FOSRestBundle compatible with Symfony 4 soon.

**Pull request merged**
