### PR TITLE
Iterator handler

### PR DESCRIPTION
**Pull request by simPod**
Adds support for this https://github.com/schmittjoh/serializer/pull/1034

### CODE REVIEW

**Comment by simPod** [comment]
needs upgrading jmsserializer first tho

**Comment by goetas** [comment]
https://github.com/schmittjoh/serializer/pull/1034 is released as 2.2.0, @simPod do you have time to complete this?

**Comment by simPod** [comment]
Sure thing, on it

**Comment by goetas** [comment]
great!

**Comment by simPod** [comment]
Build is now green. Should be ok.

**Comment by goetas** [comment]
very good!

**Pull request merged**
