### PR TITLE
Fix problem with automatically registered DocBlockDriver

### LINKED ISSUE #844: [3.9.0] InvalidArgumentException Can't use incorrect type
| Q                | A
| ---------------- | -----
| Bug report?      | yes

Hi,

After upgrade jms/serializer-bundle from 3.8.0 to 3.9.0 I'm getting exception:

```
InvalidArgumentException:
Can't use incorrect type object for collection in Doctrine\ORM\PersistentCollection:owner

  at vendor/jms/serializer/src/Metadata/Driver/DocBlockTypeResolver.php:223
  at JMS\Serializer\Metadata\Driver\DocBlockTypeResolver->expandClassNameUsingUseStatements()
     (vendor/jms/serializer/src/Metadata/Driver/DocBlockTypeResolver.php:283)
  at JMS\Serializer\Metadata\Driver\DocBlockTypeResolver->resolveType()
     (vendor/jms/serializer/src/Metadata/Driver/DocBlockTypeResolver.php:193)
  at JMS\Serializer\Metadata\Driver\DocBlockTypeResolver->resolveTypeFromTypeNode()
     (vendor/jms/serializer/src/Metadata/Driver/DocBlockTypeResolver.php:112)
  at JMS\Serializer\Metadata\Driver\DocBlockTypeResolver->getPropertyDocblockTypeHint()
     (vendor/jms/serializer/src/Metadata/Driver/DocBlockDriver.php:63)
  at JMS\Serializer\Metadata\Driver\DocBlockDriver->loadMetadataForClass()
     (vendor/jms/metadata/src/Driver/LazyLoadingDriver.php:38)
  at Metadata\Driver\LazyLoadingDriver->loadMetadataForClass()
     (vendor/jms/metadata/src/MetadataFactory.php:111)
  at Metadata\MetadataFactory->getMetadataForClass()
     (vendor/jms/serializer/src/Handler/ArrayCollectionHandler.php:75)
  at JMS\Serializer\Handler\ArrayCollectionHandler->serializeCollection()
     (vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php:205)
  at JMS\Serializer\GraphNavigator\SerializationGraphNavigator->accept()
     (vendor/jms/serializer/src/JsonSerializationVisitor.php:137)
  at JMS\Serializer\JsonSerializationVisitor->visitProperty()
     (vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php:260)
  at JMS\Serializer\GraphNavigator\SerializationGraphNavigator->accept()
     (vendor/jms/serializer/src/JsonSerializationVisitor.php:137)
  at JMS\Serializer\JsonSerializationVisitor->visitProperty()
     (vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php:260)
  at JMS\Serializer\GraphNavigator\SerializationGraphNavigator->accept()
     (vendor/jms/serializer/src/JsonSerializationVisitor.php:93)
  at JMS\Serializer\JsonSerializationVisitor->visitArray()
     (vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php:166)
  at JMS\Serializer\GraphNavigator\SerializationGraphNavigator->accept()
     (vendor/jms/serializer/src/JsonSerializationVisitor.php:93)
  at JMS\Serializer\JsonSerializationVisitor->visitArray()
     (vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php:166)
  at JMS\Serializer\GraphNavigator\SerializationGraphNavigator->accept()
     (vendor/jms/serializer/src/Serializer.php:252)
  at JMS\Serializer\Serializer->visit()
     (vendor/jms/serializer/src/Serializer.php:163)
  at JMS\Serializer\Serializer->serialize()
     (src/Infrastructure/Symfony/Controller/ApiController.php:137)
  at Infrastructure\Symfony\Controller\ApiController->serialize()
     (src/Infrastructure/Symfony/Controller/ApiController.php:112)
  at Infrastructure\Symfony\Controller\ApiController->response()
     (src/Infrastructure/Symfony/Controller/ApiController.php:101)
  at Infrastructure\Symfony\Controller\ApiController->response()
     (src/UI/API/PatientController.php:422)
  at UI\API\PatientController->orders()
     (vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:195)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:24)                
```

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Doc updated   | no
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | hopefully 🙏 
| Fixed tickets | #... 
| License       | MIT

Fixes #844
Related to #824

### CODE REVIEW

**Review by simPod — APPROVED** [review]

**Comment by simPod** [comment]
Shouldn't we also make TypedPropertiesDriver configurable btw?

**Comment by alexander-schranz** [comment]
@simPod I don't see it for the types as they can not be configured false like phpdoc:

Example:

```php
class MyClass {
     private int $test = '';
}
```

Is invalid php code and so the class is never loaded and will run into a:

> PHP Fatal error:  Default value for property of type int can only be int in Command line code on line 2
> Fatal error: Default value for property of type int can only be int in Command line code on line 2

where the following with phpdocs is valid php code which runs without any problems:

```php
class MyClass {
     /**
      * @var int
      */
     private $test = '';
}
```

**Comment by simPod** [comment]
I suppose some people might want to turn it off. We have doctrine driver configurable too. It's out of scope of this fix though.

**Comment by alexander-schranz** [comment]
Lets wait for the feedback of @goetas. What he think what the best would be to fix this issue.

**Comment by goetas** [comment]
make sense, I should have made it opt it from the beginning!

**Comment by goetas** [comment]
Regarding the TypedPropertiesDriver, i think that can stay as it is since the type correctness is enforced by php, thus should work in all the cases

**Pull request merged**
